apiVersion: v1
kind: Pod
metadata:
  name: ekart-deployment
  labels:
    app: vinay
spec:
  containers:
        - name: ekart
          image: vinay0807/shopping
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070

