---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: vinay
spec:
  containers:
        - name: ekart
          image: vinay0807/shopping
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: ekartsvc
spec:
  selector:
    app: vinay
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: LoadBalancer
