name: Git Filter Repo Cleanup

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # Required to push with GITHUB_TOKEN

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python and pip
        run: |
           git config --global user.name "Vinay C"
           git config --global user.email "vinay@gmail.com"
           git clone --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git cleaned-repo.git
           ls
           cd cleaned-repo.git
           ls -a
           git rm .env
           ls -a
           find . -name ".env"
           git log --stat --all -- .env
           wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar -O bfg.jar
           java -jar bfg.jar --delete-files .env
           git log --stat --all -- .env
           git reflog expire --expire=now --all
           git gc --prune=now --aggressive
           git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git
           git push origin --force --all
           
