name: BFG Cleanup

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # needed to push with GITHUB_TOKEN

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Download BFG Repo-Cleaner
        run: |
          curl -L -o bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar

      - name: Clone repo as bare mirror
        run: |
          git clone --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git Ekart.git
          ls -la Ekart.git

      - name: Run BFG to delete .env files
        run: |
          java -jar bfg.jar --delete-files .env Ekart.git

      - name: Cleanup after BFG
        run: |
          cd Ekart.git
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Push cleaned history back to GitHub
        run: |
          cd Ekart.git
          for ref in $(git for-each-ref --format='%(refname)' refs/pull/); do
            git update-ref -d "$ref"
          done
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git
          git symbolic-ref HEAD refs/heads/main
          git push origin --force --all
          git push origin --force --tags
