name: BFG Cleanup

on:
  workflow_dispatch:  # Manual trigger

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Download BFG Repo-Cleaner
        run: |
          curl -L -o bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar

      - name: Clone repo as a bare mirror
        run: |
          git clone --mirror https://github.com/VinayC0807/Ekart.git

      - name: Run BFG to strip blobs > 100MB
        run: |
          cd Ekart.git
          java -jar ../bfg.jar --strip-blobs-bigger-than 100M

      - name: Clean up and prepare for push
        run: |
          cd Ekart.git
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git

      - name: Push cleaned repo to a new branch
        run: |
          cd Ekart.git
          git push origin --force --mirror --no-verify
