name: BFG Cleanup

on:
  workflow_dispatch:  # Manual trigger

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Download BFG Repo-Cleaner
        run: |
          git clone --mirror https://github.com/VinayC0807/Ekart.git
          cd Ekart.git
          curl -L -o ../bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar
          java -jar ../bfg.jar --strip-blobs-bigger-than 100M .
          java -jar ../bfg.jar --delete-files .env .
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
          git push --force --all
          git push --force --tags

          
          

      

