name: Git Filter Repo Cleanup

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # Required to push with GITHUB_TOKEN

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python and pip
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git

      - name: Install git-filter-repo
        run: |
          pip install git-filter-repo

      - name: Clone repository as bare mirror
        run: |
          git clone --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git cleaned-repo.git

      - name: Run git-filter-repo to delete `.env` files
        run: |
          cd cleaned-repo.git
          git filter-repo --path my.env --invert-paths

      - name: Cleanup after rewrite
        run: |
          cd cleaned-repo.git
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Remove pull request refs (not allowed to push)
        run: |
          cd cleaned-repo.git
          for ref in $(git for-each-ref --format='%(refname)' refs/pull/); do
            git update-ref -d "$ref"
          done

      - name: Push cleaned repo back to GitHub
        run: |
          cd cleaned-repo.git
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VinayC0807/Ekart.git
          git push origin --force --all
          git push origin --force --tags
