name: Example workflow using Docker action

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Docker action
        uses: VinayC0807/action-repo@main
        with:
          MY_NAME: Vinay
