name: Print a Message

on:
 workflow_dispatch:

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - name: Print a message
        shell: cmd
        run: echo Hello from GitHub Actions using cmd.exe!
